### ISSUE TITLE
Awesome

### ISSUE THREAD

**Issue by nin9creative** [evoluteur/evolutility#10]
How close are you to a 1.0 release?  What features are currently missing?

**Comment by evoluteur** [comment]
It's almost there. I just have a few little bugs and I want to add a search feature.

Also, ideally I should include some examples w/ REST calls instead of local storage.

To really make it complete, I want to make a backend that works w/ the same model but that could be a different project all together.

It is mature enough for you can start using it. Please feel free to file any bug you find.

Thanks,
Olivier

**Comment by evoluteur** [comment]
... and I have to improve the documentation.

**Comment by matheo** [comment]
@evoluteur a little question:
The AGPL means that if I improve the library in some way, I'm forced to make that publicly available, but that doesn't cover my project right? not *all* the source code of my app, but evolutility's only. I'm ok or nope? thanks a lot for this BTW!
